server:
  #端口号
  port: 9037

##数据库连接信息
spring:
  #  profiles:
  #    active: dev
  cloud:
    gateway:
      discovery:
        locator:
          enabled: true
          # 服务名小写
          lower-case-service-id: true
      routes:
    # =====================================
      - id: SERVICEBASIC
          # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-BASIC
        predicates:
        - Path=/basic/**
        filters:
        - StripPrefix=0
      - id: SERVICEFEIGN
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-FEIGN
        predicates:
        - Path=/feign/**
        filters:
        - StripPrefix=0
      - id: SERVICEAPI
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-WEBAPI
        predicates:
        - Path=/webApi/**
        filters:
        - StripPrefix=0
      - id: SERVICECACHE
          # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-CACHE
        predicates:
        - Path=/cache/**
        filters:
        - StripPrefix=0
      - id: SERVICECOMMON
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-COMMON
        predicates:
        - Path=/common/**
        filters:
        - StripPrefix=0
      - id: SERVICEDOCTOR
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-DOCTOR
        predicates:
        - Path=/doctor/**
        filters:
        - StripPrefix=0  
        
      - id: SERVICEFILE
          # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-FILE
        predicates:
        - Path=/file/**
        filters:
        - StripPrefix=0
      - id: SERVICEFINANCE
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-FINANCE
        predicates:
        - Path=/finance/**
        filters:
        - StripPrefix=0
      - id: SERVICEINTERFACE
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-INTERFACE
        predicates:
        - Path=/interface/**
        filters:
        - StripPrefix=0    
      - id: SERVICEMANAGER
          # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-MANAGER
        predicates:
        - Path=/manager/**
        filters:
        - StripPrefix=0
      - id: SERVICEMEDICAL
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-MEDICAL
        predicates:
        - Path=/medocal/**
        filters:
        - StripPrefix=0
      - id: SERVICEORDER
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-ORDER
        predicates:
        - Path=/order/**
        filters:
        - StripPrefix=0  

      - id: SERVICEPATIENT
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-PATIENT
        predicates:
        - Path=/patient/**
        filters:
        - StripPrefix=0
      - id: SERVICEUTILS
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-UTILS
        predicates:
        
        - Path=/utils/**
        filters:
        - StripPrefix=0   
      - id: SERVICEDOCTOR
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-WEBDOCTOR
        predicates:
        
        - Path=/webDoctor/**
        filters:
        - StripPrefix=0 
      - id: SERVICEUTILS
                    # lb代表从注册中心获取服务，且已负载均衡方式转发
        uri: lb://INTER-HSP-WEBPATIENT
        predicates:
        
        - Path=/webPatient/**
        filters:
        - StripPrefix=0         
  # =====================================

  #====================================
  application:
    name: inter-hsp-gateway
eureka:
  instance:
    prefer-ip-address: true
  client:
    serviceUrl:
      defaultZone: http://admin:admin@127.0.0.1:9092/eureka/eureka
    enabled: true

# 暴露监控端点
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always
logging:
  level:
    org.springframework.cloud.gateway: debug
